databases:
  - name: make-typing_DB
    databaseName: make_typing_db
    user: make-typing
    region: singapore

services:
  - type: web
    name: make-typing
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: make-typing_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
